version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 8081:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:postgresql://db:5432/social_media_storage",
        "spring.datasource.username": "postgres",
        "spring.datasource.password": "postgres",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - postgres-db-network
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social_media_storage
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres-db-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  postgres-db-network:
    driver: bridge
volumes:
  postgres-db-volume: